server:
  port: 8088

spring:
  application:
    name: bootstrap
  messages:
    basename: i18n/messages
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      # write-dates-as-timestamps: date 会被序列化成时间戳, localTime,localDate,localDateTime会被序列化成 y,m,d,h,min,s,nano
      write-dates-as-timestamps: false
    deserialization:
      fail-on-ignored-properties: false
      adjust-dates-to-context-time-zone: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: pt@R2*7t&u*v
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: Dc&9feX9mfM&

logging:
  level:
    cn.zpeace.bootstrap: debug
